// Copyright 2023 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0



#include "snitch_cluster_raw_addrmap.h"

#define CFG_CLUSTER_NR_CORES 9
#define CFG_CLUSTER_BASE_HARTID 1
#define SNRT_BASE_HARTID CFG_CLUSTER_BASE_HARTID
#define SNRT_CLUSTER_CORE_NUM CFG_CLUSTER_NR_CORES
#define SNRT_CLUSTER_NUM 16
#define SNRT_CLUSTER_DM_CORE_NUM 1
#define SNRT_TCDM_BANK_WIDTH 8
#define SNRT_TCDM_BANK_NUM 32
#define SNRT_TCDM_HYPERBANK_NUM 1
#define SNRT_TCDM_BANK_PER_HYPERBANK_NUM 32
#define SNRT_TCDM_SIZE 0x20000
#define SNRT_TCDM_HYPERBANK_SIZE 0x20000
#define SNRT_TCDM_HYPERBANK_WIDTH (SNRT_TCDM_BANK_PER_HYPERBANK_NUM * SNRT_TCDM_BANK_WIDTH)
#define SNRT_CLUSTER_OFFSET 262144
#define SNRT_NUM_SEQUENCER_LOOPS 2
#define SNRT_NUM_SEQUENCER_INSNS 16
#define SNRT_L3_START_ADDR 0x80000000ULL
#define SNRT_L3_END_ADDR (SNRT_L3_START_ADDR + 0x80000000ULL)

#define SNRT_SUPPORTS_MULTICAST

// Software configuration
#define SNRT_LOG2_STACK_SIZE 10
