// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef SNITCH_CLUSTER_PERIPHERAL_H
#define SNITCH_CLUSTER_PERIPHERAL_H

#ifdef __cplusplus
extern "C" {
#endif

#include <assert.h>
#include <stdint.h>

// Reg - snitch_cluster_peripheral_reg::perf_cnt_en
#define SNITCH_CLUSTER_PERIPHERAL_REG__PERF_CNT_EN__ENABLE_bm 0x1
#define SNITCH_CLUSTER_PERIPHERAL_REG__PERF_CNT_EN__ENABLE_bp 0
#define SNITCH_CLUSTER_PERIPHERAL_REG__PERF_CNT_EN__ENABLE_bw 1
#define SNITCH_CLUSTER_PERIPHERAL_REG__PERF_CNT_EN__ENABLE_reset 0x1
typedef union {
  struct __attribute__((__packed__)) {
    uint64_t enable : 1;
    uint64_t : 63;
  } f;
  uint64_t w;
} snitch_cluster_peripheral_reg__perf_cnt_en_t;

// Reg - snitch_cluster_peripheral_reg::perf_cnt_sel
#define SNITCH_CLUSTER_PERIPHERAL_REG__PERF_CNT_SEL__HART_bm 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_REG__PERF_CNT_SEL__HART_bp 0
#define SNITCH_CLUSTER_PERIPHERAL_REG__PERF_CNT_SEL__HART_bw 16
#define SNITCH_CLUSTER_PERIPHERAL_REG__PERF_CNT_SEL__METRIC_bm 0xffff0000
#define SNITCH_CLUSTER_PERIPHERAL_REG__PERF_CNT_SEL__METRIC_bp 16
#define SNITCH_CLUSTER_PERIPHERAL_REG__PERF_CNT_SEL__METRIC_bw 16
typedef union {
  struct __attribute__((__packed__)) {
    uint64_t hart : 16;
    uint64_t metric : 16;
    uint64_t : 32;
  } f;
  uint64_t w;
} snitch_cluster_peripheral_reg__perf_cnt_sel_t;

// Reg - snitch_cluster_peripheral_reg::perf_cnt
#define SNITCH_CLUSTER_PERIPHERAL_REG__PERF_CNT__PERF_COUNTER_bm 0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_REG__PERF_CNT__PERF_COUNTER_bp 0
#define SNITCH_CLUSTER_PERIPHERAL_REG__PERF_CNT__PERF_COUNTER_bw 48
typedef union {
  struct __attribute__((__packed__)) {
    uint64_t perf_counter : 48;
    uint64_t : 16;
  } f;
  uint64_t w;
} snitch_cluster_peripheral_reg__perf_cnt_t;

// Regfile - snitch_cluster_peripheral_reg::perf_regs
typedef struct __attribute__((__packed__)) {
  snitch_cluster_peripheral_reg__perf_cnt_en_t perf_cnt_en[16];
  snitch_cluster_peripheral_reg__perf_cnt_sel_t perf_cnt_sel[16];
  snitch_cluster_peripheral_reg__perf_cnt_t perf_cnt[16];
} snitch_cluster_peripheral_reg__perf_regs_t;

// Reg - snitch_cluster_peripheral_reg::scratch
#define SNITCH_CLUSTER_PERIPHERAL_REG__SCRATCH__SCRATCH_bm 0xffffffff
#define SNITCH_CLUSTER_PERIPHERAL_REG__SCRATCH__SCRATCH_bp 0
#define SNITCH_CLUSTER_PERIPHERAL_REG__SCRATCH__SCRATCH_bw 32
#define SNITCH_CLUSTER_PERIPHERAL_REG__SCRATCH__SCRATCH_reset 0x0
typedef union {
  struct __attribute__((__packed__)) {
    uint64_t scratch : 32;
    uint64_t : 32;
  } f;
  uint64_t w;
} snitch_cluster_peripheral_reg__scratch_t;

// Reg - snitch_cluster_peripheral_reg::cl_clint_set
#define SNITCH_CLUSTER_PERIPHERAL_REG__CL_CLINT_SET__CL_CLINT_SET_bm 0xffffffff
#define SNITCH_CLUSTER_PERIPHERAL_REG__CL_CLINT_SET__CL_CLINT_SET_bp 0
#define SNITCH_CLUSTER_PERIPHERAL_REG__CL_CLINT_SET__CL_CLINT_SET_bw 32
typedef union {
  struct __attribute__((__packed__)) {
    uint64_t cl_clint_set : 32;
    uint64_t : 32;
  } f;
  uint64_t w;
} snitch_cluster_peripheral_reg__cl_clint_set_t;

// Reg - snitch_cluster_peripheral_reg::cl_clint_clear
#define SNITCH_CLUSTER_PERIPHERAL_REG__CL_CLINT_CLEAR__CL_CLINT_CLEAR_bm       \
  0xffffffff
#define SNITCH_CLUSTER_PERIPHERAL_REG__CL_CLINT_CLEAR__CL_CLINT_CLEAR_bp 0
#define SNITCH_CLUSTER_PERIPHERAL_REG__CL_CLINT_CLEAR__CL_CLINT_CLEAR_bw 32
typedef union {
  struct __attribute__((__packed__)) {
    uint64_t cl_clint_clear : 32;
    uint64_t : 32;
  } f;
  uint64_t w;
} snitch_cluster_peripheral_reg__cl_clint_clear_t;

// Reg - snitch_cluster_peripheral_reg::icache_prefetch_enable
#define SNITCH_CLUSTER_PERIPHERAL_REG__ICACHE_PREFETCH_ENABLE__ICACHE_PREFETCH_ENABLE_bm \
  0x1
#define SNITCH_CLUSTER_PERIPHERAL_REG__ICACHE_PREFETCH_ENABLE__ICACHE_PREFETCH_ENABLE_bp \
  0
#define SNITCH_CLUSTER_PERIPHERAL_REG__ICACHE_PREFETCH_ENABLE__ICACHE_PREFETCH_ENABLE_bw \
  1
#define SNITCH_CLUSTER_PERIPHERAL_REG__ICACHE_PREFETCH_ENABLE__ICACHE_PREFETCH_ENABLE_reset \
  0x1
typedef union {
  struct __attribute__((__packed__)) {
    uint64_t icache_prefetch_enable : 1;
    uint64_t : 63;
  } f;
  uint64_t w;
} snitch_cluster_peripheral_reg__icache_prefetch_enable_t;

// Reg - snitch_cluster_peripheral_reg::unused
#define SNITCH_CLUSTER_PERIPHERAL_REG__UNUSED__F_bm 0x1f
#define SNITCH_CLUSTER_PERIPHERAL_REG__UNUSED__F_bp 0
#define SNITCH_CLUSTER_PERIPHERAL_REG__UNUSED__F_bw 5
#define SNITCH_CLUSTER_PERIPHERAL_REG__UNUSED__F_reset 0x0
typedef union {
  struct __attribute__((__packed__)) {
    uint64_t f : 5;
    uint64_t : 59;
  } f;
  uint64_t w;
} snitch_cluster_peripheral_reg__unused_t;

// Addrmap - snitch_cluster_peripheral_reg
typedef struct __attribute__((__packed__)) {
  snitch_cluster_peripheral_reg__perf_regs_t perf_regs;
  snitch_cluster_peripheral_reg__scratch_t scratch[4];
  snitch_cluster_peripheral_reg__cl_clint_set_t cl_clint_set;
  snitch_cluster_peripheral_reg__cl_clint_clear_t cl_clint_clear;
  snitch_cluster_peripheral_reg__icache_prefetch_enable_t
      icache_prefetch_enable;
  snitch_cluster_peripheral_reg__unused_t unused;
} snitch_cluster_peripheral_reg_t;

// Instances
#define snitch_cluster_peripheral_reg                                          \
  (*(volatile snitch_cluster_peripheral_reg_t *)0x0UL)

static_assert(sizeof(snitch_cluster_peripheral_reg_t) == 0x1c0,
              "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* SNITCH_CLUSTER_PERIPHERAL_H */
